/*
 * ultrasonic.c
 *
 *      Author: Ayman_Mostafa
 */

#include "ultrasonic.h"

uint16 g_timeHigh = 0;
uint8 g_edgeCount = 0;

/*******************************************************************************
 *                              Functions Prototypes                           *
 *******************************************************************************/
/*• Description
➢ Initialize the ICU driver as required.
➢ Setup the ICU call back function.
➢ Setup the direction for the trigger pin as output pin through the GPIO driver.*/
void Ultrasonic_init(void)
{
	/* Initialize the ICU driver as required.*/
	ICU_ConfigType Config_Ptr ={F_CPU_8,RAISING};
	ICU_init(&Config_Ptr);
	/* Setup the ICU call back function.*/
	ICU_setCallBack(Ultrasonic_edgeProcessing);
	/* Setup the direction for the trigger pin as output pin through the GPIO driver.*/
	GPIO_setupPinDirection(ULTRASONIC_TRIGGER_PORT_ID,ULTRASONIC_TRIGGER_PIN_ID,PIN_OUTPUT);
}

/*• Description
➢ Send the Trigger pulse to the ultrasonic*/
void Ultrasonic_Trigger(void)
{
	GPIO_writePin(ULTRASONIC_TRIGGER_PORT_ID,ULTRASONIC_TRIGGER_PIN_ID,LOGIC_HIGH);
	_delay_ms(10);
	GPIO_writePin(ULTRASONIC_TRIGGER_PORT_ID,ULTRASONIC_TRIGGER_PIN_ID,LOGIC_LOW);
}

/*• Description
➢ Send the trigger pulse by using Ultrasonic_Trigger function.
➢ Start the measurements by the ICU from this moment*/
uint16 Ultrasonic_readDistance(void)
{
	uint16 distance=0;
	Ultrasonic_Trigger();
	// Wait for the distance measurement to complete
	while(g_edgeCount!=2);
	g_edgeCount=0;
	/*distance = 17000 x (TIMER value) x 1 x 10^-6 cm */
	distance=g_timeHigh/58+1;
	return distance;
}

/*• Description
➢ This is the call back function called by the ICU driver.
➢ This is used to calculate the high time (pulse time) generated by
the ultrasonic sensor.*/
void Ultrasonic_edgeProcessing(void)
{
	g_edgeCount++;
	if(g_edgeCount == 1)
	{
		ICU_clearTimerValue();
		/* Detect falling edge */
		ICU_setEdgeDetectionType(FALLING);
	}
	else if(g_edgeCount == 2)
	{
		g_timeHigh = ICU_getInputCaptureValue();
		/* Detect rising edge */
		ICU_setEdgeDetectionType(RAISING);
	}

}


